### ISSUE TITLE
Muvio bundle not working with Windows based Plex server

### ISSUE THREAD

**Issue by jayelayche** [piplongrun/muvio.bundle#2]
I have Muvio installed on a linux based plex server and everything works fine.  But on the windows based plex server (Plex Version 1.5.4.3596) it doesn't work.  The log files say:  cannot read model from c:\users\jlh\appdata\local\

Not sure if this is the issue.  I've refreshed all artists and updated the music folder and no videos show.  Like I said, the same agent configuration is setup on the linux server and it works, just not on the windows based plex server.

Any help or ideas would be greatly appreciated.

Thanks

**Comment by piplongrun** [comment]
Thanks for the report! I'm not a Windows user, so it'll take a bit of time to setup a Windows VM to test with. I'll get back to you!

**Comment by piplongrun** [comment]
I cannot replicate this issue on a fresh Windows 10 install. Video clips are found and added to my music library just fine. Googling the `cannot read model` message shows other Windows users have ran into similar problems: https://forums.plex.tv/discussion/209717/posters-and-summary-not-downloading (fix included, hopefully!)
